### PR TITLE
Fix spacing in README

### PR DESCRIPTION
**Pull request by AMythicDev**
The Title on the README isn't big and instead a # with the title appears

### CODE REVIEW

**Comment by golddranks** [comment]
Sorry, I'm not taking in pull requests like this during the Hacktoberfest month.

**Comment by AMythicDev** [comment]
I don't really care about Hacktoberfest. I just liked your project so I filled up the PR

**Comment by golddranks** [comment]
I see, thanks! Sorry about the cold hand. (And sorry, I noticed this late to begin with, I had already fixed it by the point I noticed this.)

**Comment by AMythicDev** [comment]
It's ok. Anyone may think that I filled up the PR because of Hacktoberfest but again no problem

**Pull request closed without merging**
